version: '2.3'
services:
  coverage:
    build:
      context: .
      target: dev
    env_file: .env
    volumes:
      - .:/go/src/github.com/datatogether/coverage
      - ./sql:/sql
    ports:
      - "$PORT:$PORT"
      - "55555:55555"
    networks:
      - back-tier
    depends_on:
      - postgres
    command: gin -i -p 55555 -a $PORT
  postgres:
    image: "postgres:9.6-alpine"
    networks:
      - back-tier

networks:
  back-tier:
